[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sparql2sql"
version = "0.2.0"
description = "SPARQL to SQL translator"
requires-python = ">=3.8"
dependencies = [
    "rdflib",
    "sqlalchemy",
    "databricks-sqlalchemy",
]